### ISSUE TITLE
[refactor] diaryList

### ISSUE THREAD

**Issue by Cho2018** [mindgarden-app/mindgarden-android#18]
**develop 브랜치에 합치기**

- [x] DiaryList 관련 구조 변경
- [x] WriteDiary : write 버튼 클릭 불가 - WriteDiaryActivity에도 @"AndroidEntryPoint"를 추가하여 해결
- [x] DiaryList : list 조회 - date 상관없이 list 조회
- [x] swipe 및 delete

Room 버전 업 및 마이그레이션
https://raphaelh.tistory.com/41
https://android-dev.tistory.com/49

**Comment by godjoy** [comment]
Good!
